<?php

add_filter( 'better-framework/product-pages/install-plugin/config', 'publisher_plugin_installer_config' );

/**
 * Ads exclusive and public plugins to plugin installer
 *
 * @param $plugins
 *
 * @return mixed
 */
function publisher_plugin_installer_config( $plugins ) {

	$plugins['js_composer']                           = array(
		'name'                   => __( 'Visual Composer', 'publisher' ),
		'slug'                   => 'js_composer',
		'required'               => TRUE,
		'description'            => __( '#1 page builder plugin for WordPress - take full control over your site.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/js_composer.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'WPBakery',
		'author_uri'             => 'http://wpbakery.com',
		'is_premium'             => TRUE,
		'type'                   => 'local',
		'version'                => '5.4.7',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/js_composer.zip' ),
	);
	$plugins['better-adsmanager']                     = array(
		'name'                   => __( 'Better Ads Manager', 'publisher' ),
		'slug'                   => 'better-adsmanager',
		'required'               => FALSE,
		'description'            => __( 'Advanced ads manager with huge options + ads blockers fallback.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-adsmanager.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'type'                   => 'local',
		'version'                => '1.17.0',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/better-adsmanager.zip' ),
		'is_premium'             => TRUE,
	);
	$plugins['better-amp']                            = array(
		'name'                   => __( 'Better AMP', 'publisher' ),
		'slug'                   => 'better-amp',
		'required'               => FALSE,
		'description'            => __( 'Enables your site to load 4x faster in mobiles!', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-amp.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-social-counter']                 = array(
		'name'                   => __( 'Better Social Counter', 'publisher' ),
		'slug'                   => 'better-social-counter',
		'required'               => FALSE,
		'description'            => __( 'Complete solution for showing social networks stats on site.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-social-counter.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
		'type'                   => 'local',
		'version'                => '1.9.8',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/better-social-counter.zip' ),
	);
	$plugins['wp-migrator-client']                    = array(
		'name'                   => __( 'Publisher Migrator', 'publisher' ),
		'slug'                   => 'wp-migrator-client',
		'required'               => FALSE,
		'description'            => __( 'Switch to Publisher without losing data or shortcodes', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/publisher-migrator.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_exclusive'           => TRUE,
		'type'                   => 'local',
		'version'                => '1.1.0',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/wp-migrator-client.zip' ),
	);
	$plugins['newsletter-pack-pro']                   = array(
		'name'                   => __( 'Newsletter Pack - Pro', 'publisher' ),
		'slug'                   => 'newsletter-pack-pro',
		'required'               => FALSE,
		'description'            => __( 'Show and manage newsletters easily.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/newsletter-pack.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
		'type'                   => 'local',
		'version'                => '1.1.1',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/newsletter-pack-pro.zip' ),
	);
	$plugins['blockquote-pack-pro']                   = array(
		'name'                   => __( 'Blockquote Pack - Pro', 'publisher' ),
		'slug'                   => 'blockquote-pack-pro',
		'required'               => FALSE,
		'description'            => __( 'The best way to show quote and citation!', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/blockquote-pack.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
		'type'                   => 'local',
		'version'                => '1.2.0',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/blockquote-pack-pro.zip' ),
	);
	$plugins['smart-lists-pack-pro']                  = array(
		'name'                   => __( 'Smart Lists Pack - Pro', 'publisher' ),
		'slug'                   => 'smart-lists-pack-pro',
		'required'               => FALSE,
		'description'            => __( 'The best way to show lists and paged posts!', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/smart-lists-pack.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
		'type'                   => 'local',
		'version'                => '1.3.1',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/smart-lists-pack-pro.zip' ),
	);
	$plugins['better-post-views']                     = array(
		'name'         => __( 'Better Post Views', 'publisher' ),
		'slug'         => 'better-post-views',
		'required'     => FALSE,
		'description'  => __( 'Count post views per day and week and show 7 days popular posts.', 'publisher' ),
		'thumbnail'    => bf_get_theme_uri( 'includes/plugins/images/better-post-views.png' ),
		'author'       => 'Better Studio',
		'author_uri'   => 'http://betterstudio.com',
		'is_exclusive' => TRUE,
		'type'                   => 'local',
		'version'                => '1.5.3',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/better-post-views.zip' ),
	);
	$plugins['better-reviews']                        = array(
		'name'         => __( 'Better Reviews', 'publisher' ),
		'slug'         => 'better-reviews',
		'required'     => FALSE,
		'description'  => __( 'Review products in 3 type with stylish design.', 'publisher' ),
		'thumbnail'    => bf_get_theme_uri( 'includes/plugins/images/better-reviews.png' ),
		'author'       => 'Better Studio',
		'author_uri'   => 'http://betterstudio.com',
		'is_exclusive' => TRUE,
		'type'                   => 'local',
		'version'                => '1.4.4',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/better-reviews.zip' ),
	);
	$plugins['financial-pack-pro']                    = array(
		'name'                   => __( 'Financial Pack - Pro', 'publisher' ),
		'slug'                   => 'financial-pack-pro',
		'required'               => FALSE,
		'description'            => sprintf( __( 'The best and complete financial widgets and shortcodes', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/financial-pack-pro.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'BetterStudio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
		'type'                   => 'local',
		'version'                => '1.1.0',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/financial-pack-pro.zip' ),
	);
	$plugins['fb-instant-articles']                   = array(
		'name'                   => __( 'Facebook Instant Articles', 'publisher' ),
		'slug'                   => 'fb-instant-articles',
		'required'               => FALSE,
		'description'            => __( 'Facebook Instant Articles support.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/fia.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Automattic, Dekode, Facebook',
		'author_uri'             => 'https://vip.wordpress.com/plugins/instant-articles/',
	);
	$plugins['better-playlist']                       = array(
		'name'        => __( 'Better Playlist', 'publisher' ),
		'slug'        => 'better-playlist',
		'required'    => FALSE,
		'description' => __( 'The best way to Youtube playlist\'s and Vimeo album\'s in WordPress', 'publisher' ),
		'thumbnail'   => bf_get_theme_uri( 'includes/plugins/images/better-playlist.png' ),
		'author'      => 'Better Studio',
		'author_uri'  => 'http://betterstudio.com',
		'is_premium'  => TRUE,
		'type'                   => 'local',
		'version'                => '1.4.2',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/better-playlist.zip' ),
	);
	$plugins['better-disqus-comments']                = array(
		'name'                   => __( 'Better Disqus Comments', 'publisher' ),
		'slug'                   => 'better-disqus-comments',
		'required'               => FALSE,
		'description'            => __( 'Use DISQUS comments for theme with this plugin.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-disqus-comments.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_exclusive'           => TRUE,
		'type'                   => 'local',
		'version'                => '1.3.0',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/better-disqus-comments.zip' ),
	);
	$plugins['better-facebook-comments']              = array(
		'name'                   => __( 'Better Facebook Comments', 'publisher' ),
		'slug'                   => 'better-facebook-comments',
		'required'               => FALSE,
		'description'            => __( 'Use Facebook comments for theme with this plugin.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-facebook-comments.png' ),
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_exclusive'           => TRUE,
		'type'                   => 'local',
		'version'                => '1.5.3',
		'local_path'             => bf_get_theme_dir( 'includes/plugins/files/better-facebook-comments.zip' ),
	);
	$plugins['custom-sidebars']                       = array(
		'name'                   => __( 'Custom sidebars', 'publisher' ),
		'slug'                   => 'custom-sidebars',
		'required'               => FALSE,
		'description'            => __( 'Create and customize sidebars for pages with easy user interface.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/custom-sidebars.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'WPMU DEV',
		'author_uri'             => 'http://premium.wpmudev.org',
		'is_compatible'          => TRUE,
	);
	$plugins['wordpress-social-login']                = array(
		'name'                   => __( 'Social Login', 'publisher' ),
		'slug'                   => 'wordpress-social-login',
		'required'               => FALSE,
		'description'            => __( 'Allow your visitors to comment and login with social networks.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/wordpress-social-login.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Miled',
		'author_uri'             => 'http://github.com/miled',
		'is_compatible'          => TRUE,
	);
	$plugins['contact-form-7']                        = array(
		'name'                   => __( 'Contact Form 7', 'publisher' ),
		'slug'                   => 'contact-form-7',
		'required'               => FALSE,
		'description'            => __( 'Just another contact form plugin. Simple but flexible.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/contact-form-7.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Takayuki Miyoshi',
		'author_uri'             => 'http://ideasilo.wordpress.com',
		'is_compatible'          => TRUE,
	);
	$plugins['onesignal-free-web-push-notifications'] = array(
		'name'                   => __( 'Push Notifications', 'publisher' ),
		'slug'                   => 'onesignal-free-web-push-notifications',
		'required'               => FALSE,
		'description'            => sprintf( __( 'OneSignal – Free Web Push Notifications is a complete push notification solution for WordPress', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/onesignal.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'OneSignal',
		'author_uri'             => 'https://onesignal.com/',
		'is_compatible'          => TRUE,
	);
	$plugins['woocommerce']                           = array(
		'name'                   => __( 'WooCommerce', 'publisher' ),
		'slug'                   => 'woocommerce',
		'required'               => FALSE,
		'description'            => __( 'Powerful and extendable eCommerce plugin that helps you sell anything.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/woocommerce.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Automattic',
		'author_uri'             => 'http://woocommerce.com',
		'is_compatible'          => TRUE,
	);
	$plugins['bbpress']                               = array(
		'name'                   => __( 'bbPress', 'publisher' ),
		'slug'                   => 'bbpress',
		'required'               => FALSE,
		'description'            => sprintf( __( 'Create forums! %s is fully compatible with bbPress.', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/bbpress.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'The bbPress Community',
		'author_uri'             => 'http://bbpress.org',
		'is_compatible'          => TRUE,
	);

	return $plugins;
}
